using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Text;
using System.Runtime.InteropServices;
using System.Windows.Forms;

/*
            ..:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::..          
           .:╔════════════════════════════════════════════════════════════════╗:.       
           :╔╩╗                                                              ╔╩╗:       
           :║▒║     ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓ ▓▓      ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓ ▓▓     ▓▓▓    ║▒║:      
          :║▒▒║     ▓▓      ▓▓    ▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓   ▓▓ ▓▓    ║▒▒║:    
         :║▒▒▒║     ▓▓▓▓▓   ▓▓▓▓▓▓▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓  ▓▓  ▓▓    ║▒▒▒║:    
        :║▒▒▒▒║     ▓▓      ▓▓    ▓▓ ▓▓      ▓▓      ▓▓     ▓▓ ▓▓ ▓▓   ▓▓    ║▒▒▒▒║:   
       :║▒▒▒▒▒║     ▓▓      ▓▓    ▓▓ ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓▓▓ ▓▓▓▓    ▓▓    ║▒▒▒▒▒║:  
       :║▒▒▒▒▒║                                                              ║▒▒▒▒▒║:  
        :║▒▒▒▒║                     • IconFontManager •                      ║▒▒▒▒║:  
         :║▒▒▒║                     -------------------                      ║▒▒▒║:    
          :║▒▒║                    Icon Font Manager CLASS                   ║▒▒║:     
           :║▒║               © Generated BY FALAH FATHEL • 2026             ║▒║:      
           :╚╦╝               |Github|www.github.com/FALCONZeroX             ╚╦╝:     
            :╚════════════════════════════════════════════════════════════════╝:'      
            '':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::''  
*/


namespace IFM
{
    /* ================================================================================ */
    /*              Custom Icon Font Manager CLASS With Memory Management               */
    /* ================================================================================ */
    public class IconFontManager : IDisposable
    {
        // Record Font In Memory [Win32 API]
        [DllImport("gdi32.dll")]
        private static extern IntPtr AddFontMemResourceEx(IntPtr pbFont, uint cbFont, IntPtr pdv, [In] ref uint pcFonts);

        private PrivateFontCollection _privateFonts = new PrivateFontCollection();
        private List<IntPtr> _fontPointers = new List<IntPtr>();
        private Dictionary<string, Font> _fonts = new Dictionary<string, Font>();
        private Dictionary<string, IntPtr> _fontPtrMap = new Dictionary<string, IntPtr>();

        //====================================================================
        //================= FONT Manage (Adding - Deletion) ==================
        //====================================================================
        public Font AddFont(string fontKey, byte[] fontData, float fontSize)
        {
            if (string.IsNullOrEmpty(fontKey))
                throw new ArgumentException("Must Have FontKey", nameof(fontKey));
            if (fontData == null || fontData.Length == 0)
                throw new ArgumentException("Font Info Is Empty", nameof(fontData));
            if (_fonts.ContainsKey(fontKey))
                return _fonts[fontKey]; 

            IntPtr fontPtr = Marshal.AllocCoTaskMem(fontData.Length);
            Marshal.Copy(fontData, 0, fontPtr, fontData.Length);

            uint numFonts = 1;
            AddFontMemResourceEx(fontPtr, (uint)fontData.Length, IntPtr.Zero, ref numFonts);

            _privateFonts.AddMemoryFont(fontPtr, fontData.Length);
            _fontPointers.Add(fontPtr);
            _fontPtrMap[fontKey] = fontPtr;

            int lastIndex = _privateFonts.Families.Length - 1;
            Font newFont = new Font(_privateFonts.Families[lastIndex], fontSize, FontStyle.Regular, GraphicsUnit.Point);
            _fonts[fontKey] = newFont;

            return newFont;
        }

        public Font GetFont(string fontKey)
        {
            if (string.IsNullOrEmpty(fontKey)) return null;
            _fonts.TryGetValue(fontKey, out Font font);
            return font;
        }

        public bool HasFont(string fontKey)
        {
            return !string.IsNullOrEmpty(fontKey) && _fonts.ContainsKey(fontKey);
        }

        public bool RemoveFont(string fontKey)
        {
            if (!_fonts.ContainsKey(fontKey)) return false;

            _fonts[fontKey]?.Dispose();
            _fonts.Remove(fontKey);

            if (_fontPtrMap.TryGetValue(fontKey, out IntPtr ptr))
            {
                _fontPtrMap.Remove(fontKey);
                _fontPointers.Remove(ptr);
                Marshal.FreeCoTaskMem(ptr);
            }
            return true;
        }

        public IEnumerable<string> GetFontKeys() => _fonts.Keys;

        public void ClearAll()
        {
            foreach (var font in _fonts.Values) font?.Dispose();
            _fonts.Clear();
            foreach (IntPtr ptr in _fontPointers) Marshal.FreeCoTaskMem(ptr);
            _fontPointers.Clear();
            _fontPtrMap.Clear();
            _privateFonts?.Dispose();
            _privateFonts = new PrivateFontCollection();
        }

        //====================================================================
        //=================== Initialization & Registration =================
        //====================================================================
        public Font RegisterAndApply(string fontKey, byte[] fontData, float fontSize, Control parent)
        {
            Font font = AddFont(fontKey, fontData, fontSize);
            ApplyToAll(parent, fontKey);
            return font;
        }

        //====================================================================
        //===================== Apply Fonts ON CONTROLS ======================
        //====================================================================
        private List<Control> GetAllControls(Control parent)
        {
            var controls = new List<Control>();
            if (parent == null) return controls;

            foreach (Control child in parent.Controls)
            {
                controls.Add(child);
                if (child.HasChildren)
                    controls.AddRange(GetAllControls(child));
            }
            return controls;
        }

        public void ApplyToAll(Control parent, string fontKey)
        {
            Font font = GetFont(fontKey);
            if (font == null) return; 

            foreach (Control ctrl in GetAllControls(parent))
            {
                ctrl.Font = font;
            }
        }

        public void ApplyToType<T>(Control parent, string fontKey) where T : Control
        {
            Font font = GetFont(fontKey);
            if (font == null) return;

            foreach (Control ctrl in GetAllControls(parent))
            {
                if (ctrl is T)
                    ctrl.Font = font;
            }
        }

        public void ApplyWhere(Control parent, string fontKey, Func<Control, bool> predicate)
        {
            if (predicate == null) return;
            Font font = GetFont(fontKey);
            if (font == null) return;

            foreach (Control ctrl in GetAllControls(parent))
            {
                if (predicate(ctrl))
                    ctrl.Font = font;
            }
        }

        public void ApplyToControl(Control control, string fontKey)
        {
            if (control == null) return;
            Font font = GetFont(fontKey);
            if (font == null) return;

            control.Font = font;
        }

        //====================================================================
        //===================== Specialized Setters (Safe) ====================
        //====================================================================
        public void SetIcon(Control control, string fontKey, string iconCode)
        {
            if (control == null) return;

            Font font = GetFont(fontKey);
            if (font == null) return; 

            control.Font = font;
            control.Text = iconCode;
        }

        public void SetIconWithText(Control control, string fontKey, string iconCode, string text)
        {
            if (control == null) return;

            Font font = GetFont(fontKey);
            if (font == null) return;

            control.Font = font;
            control.Text = string.IsNullOrEmpty(text) ? iconCode : $"{iconCode} {text}";
        }

        public void SetIcon(Control control, string fontKey, string iconCode, float fontSize)
        {
            if (control == null) return;

            Font baseFont = GetFont(fontKey);
            if (baseFont == null) return;

            control.Font = new Font(baseFont.FontFamily, fontSize, baseFont.Style);
            control.Text = iconCode;
        }

        //====================================================================
        //======================= Disposing (Cleaning) =======================
        //====================================================================
        public void Dispose()
        {
            ClearAll();
            _privateFonts?.Dispose();
            GC.SuppressFinalize(this);
        }
    }
}
